.PHONY: help build run test test-cover lint fmt tidy score score-update bench-accuracy \
	e2e-claude extension extension-e2e contract-update clean

BIN     := bin/neverseen
PKG     := ./cmd/neverseen
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
LDFLAGS := -X main.version=$(VERSION)

# Mirrors proxy.DefaultListen, for the URL to open. The agent logs the address it
# actually took, so a drift here shows up next to the wrong URL.
LISTEN  ?= 127.0.0.1:9787

help: ## Show this help
	@grep -hE '^[a-z-]+:.*?## ' $(MAKEFILE_LIST) | awk 'BEGIN{FS=":.*?## "};{printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

build: ## Build the agent binary into bin/
	go build -ldflags '$(LDFLAGS)' -o $(BIN) $(PKG)

run: build ## Run the agent and open its test page — loads .env if there is one
	@set -a; [ -f .env ] && . ./.env; set +a; \
	  addr=$${NEVERSEEN_LISTEN:-$(LISTEN)}; \
	  ( sleep 1; open "http://$$addr/test" ) & \
	  exec $(BIN) proxy

test: ## Run the whole suite with the race detector
	go test -race ./...

test-cover: ## Run the suite with coverage; the CI gate is 80%
	go test -race -coverprofile=coverage.out -covermode=atomic ./...
	@go tool cover -func=coverage.out | tail -1

lint: ## Run golangci-lint
	golangci-lint run

fmt: ## Format and tidy
	gofmt -w .
	go mod tidy

tidy: fmt

score: ## Gate per-category precision/recall against the committed floor
	go test ./internal/detector/ -run TestScoreCorpus -v

score-update: ## Rewrite that floor from the current run — explain the delta in the PR
	go test ./internal/detector/ -run TestScoreCorpus -update-score -v

bench-accuracy: ## Per-category accuracy report over the corpus
	go test ./internal/detector/ -run TestAccuracyCorpus -v

e2e-claude: ## End-to-end: the Claude CLI through the agent to the real provider (spends quota)
	NEVERSEEN_E2E_CLAUDE=1 go test ./internal/proxy/ -run TestE2EClaudeCode -v -timeout 10m

extension: ## Typecheck, test and build the browser extension into extension/dist
	cd extension && npm ci && npm run check

extension-e2e: build extension ## Drive the built extension through a real Chrome against a real agent
	cd extension && npm run e2e

contract-update: ## Rewrite the recorded extension exchanges from this run — explain the delta in the PR
	go test ./internal/proxy/ -run TestExtensionContract -update-contract -v


# THIRD_PARTY_LICENSES reproduces the notice of every module linked into the
# binaries, because MIT and BSD both require it to travel with a binary
# distribution and .goreleaser.yml ships the file. Generated and committed, the
# way the tray icons are: a release must not depend on a toolchain having been
# run.
#
# The module set is the union over the platforms goreleaser builds, not this
# machine's — systray and dbus are reached only on some of them, and a file
# generated on a Mac would omit what a Linux user's binary actually links. It is
# `go list -deps ./cmd/...` rather than `go list -m all`, because the latter also
# reports test-only modules: yaml.v3 is read by the corpus suite and reaches no
# binary, and gopkg.in/check.v1 is yaml's own test dependency.
third-party: ## Regenerate THIRD_PARTY_LICENSES from the module cache
	@{ \
	  echo "Third-party licenses"; \
	  echo "===================="; \
	  echo; \
	  echo "Generated by \`make third-party\` — do not edit by hand."; \
	  echo; \
	  echo "Every module below is linked into the binaries this repository ships."; \
	  echo "Its licence requires the notice to accompany a binary distribution, so"; \
	  echo "this file travels in every release archive."; \
	  echo; \
	  for m in $$(for os in linux darwin windows; do \
	      GOOS=$$os go list -deps -f '{{if .Module}}{{if not .Module.Main}}{{.Module.Path}}{{end}}{{end}}' ./cmd/... 2>/dev/null; \
	    done | sort -u); do \
	    dir=$$(go list -m -f '{{.Dir}}' $$m); \
	    ver=$$(go list -m -f '{{.Version}}' $$m); \
	    lic=$$(ls $$dir | grep -iE '^(LICEN[CS]E|COPYING)' | head -1); \
	    echo "--------------------------------------------------------------------"; \
	    echo "$$m $$ver"; \
	    echo "--------------------------------------------------------------------"; \
	    echo; \
	    cat "$$dir/$$lic"; \
	    echo; \
	  done; \
	} > THIRD_PARTY_LICENSES
	@echo "THIRD_PARTY_LICENSES: $$(grep -c '^' THIRD_PARTY_LICENSES) lines, $$(grep -c '^--------' THIRD_PARTY_LICENSES | awk '{print $$1/2}') modules"
clean: ## Remove build artefacts
	rm -rf bin dist coverage.out coverage.html
